"""Create users table

Revision ID: 6755955ad2b4
Revises: 
Create Date: 2025-05-20 09:50:35.139777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6755955ad2b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('localizacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('mecanicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('equipamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('localizacao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['localizacao_id'], ['localizacoes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('ordens_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_os', sa.String(length=20), nullable=False),
    sa.Column('solicitante', sa.String(length=100), nullable=False),
    sa.Column('localizacao_id', sa.Integer(), nullable=False),
    sa.Column('tipo_manutencao', sa.String(length=50), nullable=False),
    sa.Column('tipo_parada', sa.String(length=50), nullable=False),
    sa.Column('equipamento_id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('mecanico_id', sa.Integer(), nullable=True),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_termino', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('sap', sa.String(length=50), nullable=True),
    sa.Column('tempo_manutencao', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['equipamento_id'], ['equipamentos.id'], ),
    sa.ForeignKeyConstraint(['localizacao_id'], ['localizacoes.id'], ),
    sa.ForeignKeyConstraint(['mecanico_id'], ['mecanicos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_os')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ordens_servico')
    op.drop_table('equipamentos')
    op.drop_table('users')
    op.drop_table('mecanicos')
    op.drop_table('localizacoes')
    # ### end Alembic commands ###
